"""
Sandbox telemetry collector.

This module receives and normalizes telemetry generated by
the isolated malware-analysis environment.

It does NOT execute suspicious files.
"""

from datetime import datetime

from src.sandbox.telemetry_schema import (
    create_empty_telemetry,
    add_process_event,
    add_file_event,
    add_registry_event,
    add_network_event,
    add_dns_event,
    add_persistence_event,
)


def current_timestamp():
    """
    Return the current UTC timestamp.

    A timestamp allows us to reconstruct the sequence of
    events produced during sandbox execution.
    """

    return datetime.utcnow().isoformat() + "Z"


def record_process(telemetry, process_name, pid=None, parent_pid=None,
                   command_line=None):
    """
    Record a process creation event.

    Parameters:
        process_name: Name of the process.
        pid: Process ID if available.
        parent_pid: Parent process ID if available.
        command_line: Command line used to start the process.
    """

    event = {
        "timestamp": current_timestamp(),
        "process_name": process_name,
        "pid": pid,
        "parent_pid": parent_pid,
        "command_line": command_line,
    }

    add_process_event(telemetry, event)


def record_file_event(telemetry, action, path, process_name=None):
    """
    Record a filesystem event.

    Examples:
        create
        modify
        delete
        rename
    """

    event = {
        "timestamp": current_timestamp(),
        "action": action,
        "path": path,
        "process_name": process_name,
    }

    add_file_event(telemetry, event)


def record_registry_event(telemetry, action, key, value_name=None,
                          process_name=None):
    """
    Record a Windows Registry event.

    Parameters:
        action: Operation such as create or modify.
        key: Registry key path.
        value_name: Registry value involved.
        process_name: Process responsible for the operation.
    """

    event = {
        "timestamp": current_timestamp(),
        "action": action,
        "key": key,
        "value_name": value_name,
        "process_name": process_name,
    }

    add_registry_event(telemetry, event)


def record_network_event(telemetry, destination, port,
                         protocol="TCP", process_name=None):
    """
    Record a network connection event.

    This captures the destination and process responsible
    for the connection.
    """

    event = {
        "timestamp": current_timestamp(),
        "destination": destination,
        "port": port,
        "protocol": protocol,
        "process_name": process_name,
    }

    add_network_event(telemetry, event)


def record_dns_event(telemetry, domain, resolved_ips=None,
                     process_name=None):
    """
    Record a DNS lookup.

    resolved_ips contains the IP addresses returned by DNS,
    when they are available.
    """

    event = {
        "timestamp": current_timestamp(),
        "domain": domain,
        "resolved_ips": resolved_ips or [],
        "process_name": process_name,
    }

    add_dns_event(telemetry, event)


def record_persistence_event(telemetry, persistence_type,
                             location, process_name=None):
    """
    Record a possible persistence mechanism.

    Examples:
        run_key
        scheduled_task
        service
        startup_folder
    """

    event = {
        "timestamp": current_timestamp(),
        "type": persistence_type,
        "location": location,
        "process_name": process_name,
    }

    add_persistence_event(telemetry, event)


def create_demo_telemetry():
    """
    Create synthetic telemetry for testing.

    This function deliberately does not execute any file.
    """

    telemetry = create_empty_telemetry()

    record_process(
        telemetry,
        process_name="sample.exe",
        pid=1500,
        parent_pid=1200,
        command_line="sample.exe"
    )

    record_process(
        telemetry,
        process_name="powershell.exe",
        pid=1600,
        parent_pid=1500,
        command_line="powershell.exe -NoProfile"
    )

    record_file_event(
        telemetry,
        action="create",
        path="C:\\Temp\\sample.dat",
        process_name="sample.exe"
    )

    record_registry_event(
        telemetry,
        action="modify",
        key="HKCU\\Software\\Example",
        value_name="Sample",
        process_name="sample.exe"
    )

    record_network_event(
        telemetry,
        destination="203.0.113.10",
        port=443,
        protocol="TCP",
        process_name="sample.exe"
    )

    record_dns_event(
        telemetry,
        domain="example.test",
        resolved_ips=["203.0.113.10"],
        process_name="sample.exe"
    )

    record_persistence_event(
        telemetry,
        persistence_type="run_key",
        location="HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
        process_name="sample.exe"
    )

    return telemetry


if __name__ == "__main__":

    telemetry = create_demo_telemetry()

    print("\n" + "=" * 60)
    print("SANDBOX TELEMETRY COLLECTOR TEST")
    print("=" * 60)

    for category, events in telemetry.items():

        print(f"\n{category}: {len(events)} event(s)")

        for event in events:
            print(f"  {event}")

    print("\n" + "=" * 60)
